apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote
  namespace: kargo-helm
spec:
  vars:
  - name: image
    value: ghcr.io/linaewen19/guestbook
  - name: repoURL
    value: https://github.com/linaewen19/kargo-helm.git
  - name: branch
    value: main

  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - branch: ${{ vars.branch }}
        path: ./out
  - uses: yaml-update
    as: update-image
    config:
      path: ./out/env/${{ ctx.stage }}/values.yaml
      updates:
      - key: image.tag
        value: ${{ imageFrom( vars.image ).Tag }}
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: "updated ${{ ctx.stage }} guestbook to ${{ imageFrom( vars.image ).Tag }}"
  - uses: git-push
    as: push
    config:
      path: ./out
      generateTargetBranch: true
  - uses: git-open-pr
    as: open-pr
    config:
      repoURL: ${{ vars.repoURL }}
      sourceBranch: ${{ task.outputs.push.branch }}
      targetBranch: ${{ vars.branch }}
      provider: github
      title: "Promote ${{ ctx.stage }}"
  - if: ${{ task.outputs['open-pr'] != nil }}
    uses: git-wait-for-pr
    as: wait
    config:
      repoURL: ${{ vars.repoURL }}
      provider: github
      prNumber: ${{ task.outputs['open-pr'].pr.id }}
  - uses: argocd-update
    config:
      apps:
      - name: kargo-helm-${{ ctx.stage }}
