apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook-dev
  namespace: kargo-helm
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/linaewen19/guestbook
      imageSelectionStrategy: NewestBuild
      allowTagsRegexes:
      - ^dev-

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook-preprod
  namespace: kargo-helm
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/linaewen19/guestbook
      imageSelectionStrategy: NewestBuild
      allowTagsRegexes:
      - ^preprod-

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook-prod
  namespace: kargo-helm
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/linaewen19/guestbook
      imageSelectionStrategy: NewestBuild
      allowTagsRegexes:
      - ^prod-

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: features
  namespace: kargo-helm
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 20
      repoURL: https://github.com/linaewen19/kargo-helm.git
      includePaths:
      - base/feature-flags.yaml
